FROM alpine:latest AS builder

RUN apk add go git

RUN cd /tmp && \
  git clone https://github.com/emersion/hydroxide.git && \
  cd hydroxide && \
  CGO_ENABLED=0 go build ./cmd/hydroxide

FROM gcr.io/distroless/static-debian12:latest

COPY --from=builder /tmp/hydroxide/hydroxide /usr/bin/hydroxide

USER nonroot
WORKDIR /home/nonroot

ENTRYPOINT [ "/usr/bin/hydroxide" ]
