FROM alpine:latest

RUN apk add -U --no-cache navidrome && \
  echo "nonroot:x:65534:65534:nonroot:/home/nonroot:/usr/sbin/nologin" | tee -a /etc/passwd && \
  echo "nonroot:x:65534:nonroot" | tee -a /etc/group

RUN mkdir -p /var/lib/navidrome && chown nonroot:nonroot /var/lib/navidrome

WORKDIR /var/lib/navidrome
USER nonroot

ENTRYPOINT [ "navidrome" ]
