name: Build Hydroxide image

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: "50 5 * * 0"
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/reusable-build-image.yml
    secrets: inherit
    with:
      image-name: hydroxide
      image-desc: Minimal alpine-based hydroxide image
      publish: ${{ github.event_name != 'pull_request' }}
