name: Build Radicale image

on:
  push:
    paths:
      - "images/radicale"
  pull_request:
    branches:
      - main
  schedule:
    - cron: "50 5 * * 0"
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yaml
    secrets: inherit
    with:
      image-name: radicale
      image-desc: Minimal alpine-based radicale image
      publish: ${{ github.event_name != 'pull_request' }}
